[images]
  remote_images = [
    "https://ext.same-assets.com/2516256495/.*",
    "https://ext.same-assets.com/261593853/.*",
    "https://ext.same-assets.com/80099309/.*"
  ]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
